/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.devo.elmart.gsdipri;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
